from dataclasses import dataclass
from datetime import datetime


class EventTypes:
    USER_RETURNED = "USER_RETURNED"
    USER_LEFT = "USER_LEFT"

    PERSON_PRESENT = "PERSON_PRESENT"
    PERSON_ABSENT = "PERSON_ABSENT"

    UNKNOWN_PERSON_ENTERED = "UNKNOWN_PERSON_ENTERED"
    CURIOSITY_TRIGGERED = "CURIOSITY_TRIGGERED"

    SPEECH_DETECTED = "SPEECH_DETECTED"
    SPEECH_STARTED = "SPEECH_STARTED"
    SPEECH_ENDED = "SPEECH_ENDED"

    TEXT_RECEIVED = "TEXT_RECEIVED"
    TEXT_RESPONSE = "TEXT_RESPONSE"

    SPEAKING_STARTED = "SPEAKING_STARTED"
    SPEAKING_ENDED = "SPEAKING_ENDED"

    OWNER_VOICE_DETECTED = "OWNER_VOICE_DETECTED"
    UNKNOWN_VOICE_DETECTED = "UNKNOWN_VOICE_DETECTED"

    TAP_DETECTED = "TAP_DETECTED"


@dataclass
class Event:
    type: str
    data: dict
    timestamp: datetime
